# Generated by Django 5.0.3 on 2024-05-20 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        ('useroperations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_status',
            name='Geo_fence_distance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='child_id',
            field=models.ForeignKey(default='C000000', on_delete=django.db.models.deletion.CASCADE, to='useroperations.children'),
            preserve_default=False,
        ),
    ]
