# Generated by Django 5.0.3 on 2024-05-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_account_status_geo_fence_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_status',
            name='Geo_fenced_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
