# Generated by Django 5.0.3 on 2024-05-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_account_status_geo_fenced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
