# Generated by Django 5.0.3 on 2024-05-17 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useroperations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_age', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('question', models.TextField()),
                ('choice_a', models.TextField()),
                ('choice_b', models.TextField()),
                ('choice_c', models.TextField()),
                ('choice_d', models.TextField()),
                ('correct', models.CharField(max_length=10)),
                ('attempts', models.IntegerField()),
                ('correct_attempts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='safety_tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_age', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('cartegory', models.CharField(max_length=255)),
                ('tip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='gaming_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_age', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('game', models.CharField(max_length=100)),
                ('child_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='useroperations.children')),
            ],
        ),
    ]
